### Este archivo funciona con la extension de VS-CODE
### REST-CLIENT

#################### AUTH API ####################

### Get Users
GET http://localhost:8080/auth

### Delete Users
DELETE http://localhost:8080/auth

### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
	"email": "jomiantoca2011@gmail.com",
	"password": "123456"
}

### Register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
	"name": "Testing Man",
	"email": "testing@test.com",
	"password": "123456"
}

##################################################

#################### USER API ####################

### update Balance
PUT http://localhost:8080/user/updateBalance
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YmQ4MDI3YmNlZWRkN2IzNzUwODRjMiIsIm5hbWUiOiJKb21pYW5UQyIsImJhbGFuY2UiOjI0MDAwLCJpYXQiOjE3MDcxNjM2OTgsImV4cCI6MTcwNzE3NDQ5OH0.AvahXbxckIk6iEAusVn2S6R5rsupjyFiOhtcD15lHj0
Content-Type: application/json

{
	"movement": "INCOME",
	"mount": "100"
}

##################################################

################ TRANSACTIONS API ################

### Get Transactions
POST http://localhost:8080/transaction
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YzZhOTNmNTYxN2JiOTZjZWMwMTlhNyIsIm5hbWUiOiJUZXN0aW5nIE1hbiIsImJhbGFuY2UiOjAsImlhdCI6MTcwNzUxODI4NSwiZXhwIjoxNzA3NTI5MDg1fQ.cvt0HyAssv497QCkMTGvRBDBitHiXpQq7_iBZ72iCus

### Get Total Transactions by Method
POST http://localhost:8080/transaction/total
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YmQ4MDI3YmNlZWRkN2IzNzUwODRjMiIsIm5hbWUiOiJKb21pYW5UQyIsImJhbGFuY2UiOjcwMDAwMCwiaWF0IjoxNzA3NTE2NDM2LCJleHAiOjE3MDc1MjcyMzZ9.OU5nrHaNdkxSXb_aOe112-5sKHv-ebk7ffV_4TbM-0Q

### Get Last Month Transactions
POST http://localhost:8080/transaction/lastMonth
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YmQ4MDI3YmNlZWRkN2IzNzUwODRjMiIsIm5hbWUiOiJKb21pYW5UQyIsImJhbGFuY2UiOjc3Nzc3NywiaWF0IjoxNzA3NTM3MTQ5LCJleHAiOjE3MDc1NDc5NDl9.-8J9F6T1VsrXDPcnK7H2jzJukquSfl33XKPjPEGithU

### Create Transaction
POST http://localhost:8080/transaction/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YmQ4MDI3YmNlZWRkN2IzNzUwODRjMiIsIm5hbWUiOiJKb21pYW5UQyIsImJhbGFuY2UiOjI0MDAwLCJpYXQiOjE3MDcxNjM2OTgsImV4cCI6MTcwNzE3NDQ5OH0.AvahXbxckIk6iEAusVn2S6R5rsupjyFiOhtcD15lHj0
Content-Type: application/json

{
	"method": "CASH",
	"movement": "COST",
	"mount": "2200",
	"description": "Egreso de dinero"
	//"date": "2014-9-29"
}

//"user": "65bd539c03426b5b68b9188c",
//"method": "CARD", 					CARD, CASH
//"movement": "INCOME",					INCOME, COST
//"mount": "100",
//"description": "Ingreso de dinero"  	OPCIONAL
//"date": "2014-9-29" 					OPCIONAL -> YYYY-MM-DD

### Update Transaction
PUT http://localhost:8080/transaction/update
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YmQ4MDI3YmNlZWRkN2IzNzUwODRjMiIsIm5hbWUiOiJKb21pYW5UQyIsImJhbGFuY2UiOjI0MDAwLCJpYXQiOjE3MDcxNjM2OTgsImV4cCI6MTcwNzE3NDQ5OH0.AvahXbxckIk6iEAusVn2S6R5rsupjyFiOhtcD15lHj0
Content-Type: application/json

{
	"id": "65c141389cb4336b6bd11b8b",
	"method": "CASH",
	"movement": "COST",
	"mount": "500000"
}

### Delete Transactions
DELETE http://localhost:8080/transaction/delete
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YmQ4MDI3YmNlZWRkN2IzNzUwODRjMiIsIm5hbWUiOiJKb21pYW5UQyIsImJhbGFuY2UiOjI0MDAwLCJpYXQiOjE3MDcxNjM2OTgsImV4cCI6MTcwNzE3NDQ5OH0.AvahXbxckIk6iEAusVn2S6R5rsupjyFiOhtcD15lHj0
Content-Type: application/json

{
	"id": "65c141389cb4336b6bd11b8b"
}
##################################################
