### Este archivo funciona con la extension de VS-CODE
### REST-CLIENT

#################### AUTH API ####################

### Get Users
GET http://localhost:8080/auth

### Delete Users
DELETE http://localhost:8080/auth

### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
	"email": "jomiantoca2011@gmail.com",
	"password": "123456"
}

### Register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
	"name": "Miguel Angel",
	"email": "jomiantoca2011@gmail.com",
	"password": "123456"
}

##################################################

#################### USER API ####################

### update Balance
PUT http://localhost:8080/user/updateBalance
Content-Type: application/json

{
	"userId": "65b96bee7fc2a5cb8e9a7c31",
	"movement": "INCOME",
	"mount": "200"
}

##################################################

################ TRANSACTIONS API ################

### Get Transactions
POST http://localhost:8080/transaction
Content-Type: application/json

{
	"user": "65b96bee7fc2a5cb8e9a7c31"
}

### Create Transaction
POST http://localhost:8080/transaction/create
Content-Type: application/json

{
	"user": "65b96bee7fc2a5cb8e9a7c31",
	"movement": "INCOME",
	"mount": "10000",
	"description": "Salary"
}

### Update Transaction  "date": "2024-01-27T01:04:16.073Z"
PUT http://localhost:8080/transaction/update
Content-Type: application/json

{
	"id": "65b46fd448a71dcb62529bd8",
	"movement": "INCOME",
	//"mount": 100,
	"description": "Pepsi Actions"
}

### Delete Transactions
DELETE http://localhost:8080/transaction/delete
Content-Type: application/json

{
	"id": "65b9666565b366858dba554e"
}
##################################################
